// The ONLY client module that imports data/*. Every other module reads data from here, so a data module
// can be added, renamed or made lazy in one place. Import paths carry no ?v= suffix: the build stamp lives on
// the entry script and stylesheet links only.
//
// Not imported statically (they are not part of first paint, MC-PERF budget G8):
//   * data/legal-pathway.js and data/context.js: drawer-only. loadDrawerData() fetches them once, on first use.
//   * data/reciprocity.js, data/land-standing.js and data/region-depth.js: 77 KB brotli of prose the drawer and the compare view
//     read. loadFullData() fetches them on first use. First paint needs only "Whose land" and the first sentence of "It asks of
//     you" per region, which data/load-slim.js carries (generated by scripts/gen_load_slim.mjs; salutation() reads it itself).

import { regions, values, criteria } from '../data/regions.js';
import { cardAsks } from '../data/load-slim.js';
import * as v1Module from '../data/v1-lookup.js';
// v1Meta is written by scripts/gen_v1_lookup.mjs; a namespace import keeps an older generated file (without it) loading.
const v1Lookup = v1Module.v1Lookup;
const v1Meta = v1Module.v1Meta || {};
import { sources, sourceAliases, sourceIdFor, licenseOf, licenseUrlOf } from '../data/sources.js';
import { layerSources, layerSourceById, panelLayerSources, layerSourceLine } from '../data/layer-sources.js';
import { bioregions, bioregionSources, biomeNames } from '../data/bioregions.js';
import { PRESETS } from '../data/presets.js';

export {
  regions, values, criteria,
  cardAsks, v1Lookup, v1Meta,
  sources, sourceAliases, sourceIdFor, licenseOf, licenseUrlOf,
  layerSources, layerSourceById, panelLayerSources, layerSourceLine,
  bioregions, bioregionSources, biomeNames,
  PRESETS,
};

let _drawerData = null;
let _fullData = null;

// { regionDepth, landStanding, reciprocity, reciprocityKindLabels, reciprocityProtocols }: the full prose behind the cards,
// for the drawer and the compare view. One import per module on the first call; the same promise afterwards.
export function loadFullData() {
  if (!_fullData) {
    _fullData = Promise.all([
      import('../data/region-depth.js'),
      import('../data/land-standing.js'),
      import('../data/reciprocity.js'),
    ]).then(([rd, ls, rc]) => ({
      regionDepth: rd.regionDepth,
      landStanding: ls.landStanding,
      reciprocity: rc.reciprocity,
      reciprocityKindLabels: rc.kindLabels,
      reciprocityProtocols: rc.protocols,
    }));
  }
  return _fullData;
}

// { legalPathway, context } for the region drawer. Both modules are imported on the first call and the
// same promise is returned afterwards.
export function loadDrawerData() {
  if (!_drawerData) {
    _drawerData = Promise.all([
      import('../data/legal-pathway.js'),
      import('../data/context.js'),
    ]).then(([lp, cx]) => ({ legalPathway: lp.legalPathway, context: cx.context }));
  }
  return _drawerData;
}
