import bio_env
import json
d=json.load(open('out/final/reciprocity.json'))
hdr='''// Reciprocity layer, added 2026-10 beside land-standing.js (which keeps territory / tenure / entry / obligation / source).
// QUALITATIVE ONLY: never scored, ranked, weighted, summed or used as a filter. No personal contacts: every entry in
// firstConversations is a public organisation or protocol, and a link is a pointer, never an introduction.
//
// DRAFT status: generated by prototype/scripts/bio/build_reciprocity.py from pages opened 2026-10-04.
// `status: 'draft'` entries must be re-checked by the BIO-2 data WP (links in a browser, text against the final
// land-standing.js) before `status` is set to 'verified'. The site renders only entries that carry status 'verified'.
//
// Schema per region id:
//   territoryShort : string, <= 9 words. A short noun phrase for cards and headers ("Held by ..." is a design choice, not data).
//                    Every proper noun must also occur in landStanding[id].territory (checked by scripts/check_reciprocity.mjs).
//   contested      : null | { text, sources:[{label,url}], flag? }  honest statement where host authority is disputed or overlapping.
//   trajectory     : null | { text, kind:'return'|'recognition'|'revival'|'pressure', sources:[...] }  sourced direction of change
//                    for the people already there (land return, recognition, depopulation-and-renewal, displacement). Words only.
//   firstConversations : [{ name, kind, url, what, checked, via }]  public bodies and protocols to learn from FIRST.
//                    kind: host | regulator | access | commons | community | regional | network | language | heritage | protocol
//   notThere       : null | { forms:[string], basis:[{label,url}], flag? }  arrival forms for which the honest answer is "not there".
//                    null means "not yet researched", never "nothing to say".
//   claims         : [{ field, claim, label, url }]  per-claim sources for the base Land standing fields.
//   reviewed, status

export const kindLabels = {
  host: "Host nation or community",
  regulator: "Body that sets the rules",
  access: "Land-access or welcome programme",
  commons: "Commons or shared-water body",
  community: "Community already there",
  regional: "Regional development body",
  network: "Network or association",
  language: "Language and culture body",
  heritage: "Heritage and village body",
  protocol: "Protocol or reference"
};

export const protocols = [
  { name: "UN Declaration on the Rights of Indigenous Peoples", url: "https://social.desa.un.org/issues/indigenous-peoples/united-nations-declaration-on-the-rights-of-indigenous-peoples", what: "The Declaration adopted by the General Assembly on 13 September 2007; free, prior and informed consent runs through it.", checked: "2026-10-04" },
  { name: "Canada: United Nations Declaration on the Rights of Indigenous Peoples Act", url: "https://laws-lois.justice.gc.ca/eng/acts/U-2.2/", what: "Canadian federal statute affirming the Declaration as a universal international human rights instrument.", checked: "2026-10-04" },
  { name: "Global Indigenous Data Alliance: CARE Principles", url: "https://www.gida-global.org/", what: "Collective benefit, authority to control, responsibility, ethics: principles for Indigenous control of Indigenous data.", checked: "2026-10-04" },
  { name: "Native Land Digital: territory acknowledgement guide", url: "https://native-land.ca/resources/territory-acknowledgement/", what: "A guide from a resource to learn more about Indigenous territories, languages, lands and ways of life.", checked: "2026-10-04" }
];

export const reciprocity = '''
open('out/final/reciprocity.js','w').write(hdr+json.dumps(d,indent=2,ensure_ascii=False)+';\n')
