#!/usr/bin/env node
// Generator for data/load-slim.js: the two things the first paint needs from the big reciprocity data, and nothing else.
//
// Every region card shows "Whose land" (the salutation) and the first sentence of "It asks of you". Reading those from
// data/reciprocity.js, data/land-standing.js and data/region-depth.js put 77 KB (brotli) of drawer-sized prose on the
// critical path of the home page (MC-PERF, G8: JS at most 440,000 B brotli). This module carries just the two derived
// strings per region; the full modules load when the drawer or the compare view opens (src/data.js loadFullData()).
//
//   salutations[id] = lib/salutation.js salutationFrom(reciprocity[id], landStanding[id])   { text, short, contested }
//   cardAsks[id]    = the first sentence of regionDepth[id].asks (same rule as src/ui/region-grid.js firstSentence)
//
//   node scripts/gen_load_slim.mjs [--root DIR] [--out FILE] [--check] [--write]
//
//   --root DIR   read data/*.js and lib/salutation.js from DIR (default prototype/)
//   --out FILE   write the generated text to FILE (nothing else is touched)
//   --check      generate in memory and compare with <root>/data/load-slim.js; write nothing; exit 1 on any difference
//   --write      write <root>/data/load-slim.js
// Without --out, --check or --write the text goes to stdout. Deterministic: ids in the order of data/regions.js.
//
// Data and lib modules are imported from <root> only (never from src/), so this runs before src/data.js can load.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

// The first sentence of a text. Kept in step with src/ui/region-grid.js firstSentence; tests/core/load-slim.test.mjs
// compares the two on every region, so a change to one that is not made to the other fails there.
const ABBREV = /(?:\b(?:St|Mr|Mrs|Ms|Dr|No|Nos|vs|etc|approx|Ltd|Co|Inc|Fig|cf|ca|c|e\.g|i\.e)|\b[A-Z])\.$/;
export function firstSentence(text) {
  const s = String(text == null ? '' : text).replace(/\s+/g, ' ').trim();
  if (!s) return '';
  let end = -1;
  const re = /[.!?](?=\s+["“‘'(]?[A-ZÀ-Þ0-9]|\s*$)/g;
  let m;
  while ((m = re.exec(s))) {
    if (m[0] === '.' && ABBREV.test(s.slice(0, m.index + 1))) continue;
    end = m.index;
    break;
  }
  let one = (end < 0 ? s : s.slice(0, end + 1)).replace(/[.]$/, '');
  if (one.length > 150 && one.includes(':')) one = one.split(':')[0];
  return one + '.';
}

const HEADER =
  `// AUTO-GENERATED by scripts/gen_load_slim.mjs. Do not edit by hand.\n` +
  `// Re-run that script after any change to data/reciprocity.js, data/land-standing.js, data/region-depth.js or the\n` +
  `// salutation rule in lib/salutation.js (node scripts/gen_load_slim.mjs --write). tests/core/load-slim.test.mjs checks it.\n` +
  `// What the home page needs at first paint, so the full reciprocity data stays off its critical path (MC-PERF).\n`;

export async function build(root) {
  const imp = (rel) => import(pathToFileURL(join(root, rel)).href);
  const [{ regions }, { reciprocity }, { landStanding }, { regionDepth }, { salutationFrom }] = await Promise.all([
    imp('data/regions.js'), imp('data/reciprocity.js'), imp('data/land-standing.js'), imp('data/region-depth.js'), imp('lib/salutation.js'),
  ]);
  const sal = {};
  const asks = {};
  for (const r of regions) {
    sal[r.id] = salutationFrom(reciprocity[r.id], landStanding[r.id]);
    const d = regionDepth[r.id];
    const one = d && d.asks ? firstSentence(d.asks) : '';
    if (one) asks[r.id] = one;
  }
  const body = (o) => '{\n' + Object.entries(o).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n') + '\n}';
  return `${HEADER}\nexport const salutations = ${body(sal)};\n\nexport const cardAsks = ${body(asks)};\n`;
}

async function main() {
  const a = process.argv.slice(2);
  const opt = (n) => { const i = a.indexOf(n); return i >= 0 ? a[i + 1] : undefined; };
  const root = resolve(opt('--root') || join(here, '..'));
  // lib/salutation.js imports data/load-slim.js; before the first --write it may not exist, so give the import a stub.
  const target = join(root, 'data/load-slim.js');
  if (!existsSync(target)) writeFileSync(target, 'export const salutations = {};\nexport const cardAsks = {};\n');
  const text = await build(root);
  if (a.includes('--check')) {
    const disk = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (disk === text) { console.log('gen_load_slim: data/load-slim.js is current'); return 0; }
    console.error('gen_load_slim: data/load-slim.js is stale; run node scripts/gen_load_slim.mjs --write'); return 1;
  }
  if (opt('--out')) writeFileSync(resolve(opt('--out')), text);
  else if (a.includes('--write')) writeFileSync(target, text);
  else process.stdout.write(text);
  return 0;
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) process.exit(await main());
