#!/usr/bin/env node
// Generator for data/v1-lookup.js: the per-jurisdiction (V1) layers as one small ESM module.
//
// The six qualitative layers live in data/processed/*.json (and hospital-proximity.geojson). Region pages, the edge
// functions' tests and the test suite read those files directly. The browser only needs four of their fields to run the
// qualitative filters, so the client lookup carries exactly those and nothing else (the full lookup was 146 KB).
//
//   node scripts/gen_v1_lookup.mjs [--mode client|full] [--root DIR] [--out FILE] [--check] [--write]
//
//   --mode client   (default) the slim lookup the app imports:
//                     v1Lookup.legal_ownership[id]   = { foreign_ownership: { allowed }, regulatory_direction }
//                     v1Lookup.land_cost[id]         = { affordability_band }
//                     v1Lookup.climate_buffering[id] = { buffering_strength }
//                     v1Meta.affordability_band      = { unit, edges }  or  { relative: true }
//                   (the band definition is read from data/processed/land-cost.metadata.yaml, key `band_edges`)
//   --mode full     every record of all seven layers, byte for byte what scripts/gen_region_pages.mjs wrote before the
//                   lookup moved here (kept so the extraction can be proven against the 6bce1a3 file)
//   --root DIR      read data/processed/* (and data/regions.js for the coverage check) from DIR instead of prototype/
//   --out FILE      write the generated text to FILE (nothing else is touched)
//   --check         generate in memory and compare with the file on disk (<root>/data/v1-lookup.js, or --out FILE);
//                   write nothing; exit 1 with the head of a unified diff on any difference
//   --write         write <root>/data/v1-lookup.js (the integration step only; every other caller uses --out)
//
// Without --out, --check or --write the text goes to stdout. Client mode refuses (exit 1) to emit a lookup that does
// not cover every region of <root>/data/regions.js in every layer exactly once, or that holds a value outside the layer
// enums the four filters accept. The output is deterministic: running it twice gives the same bytes.

import { readFileSync, writeFileSync, existsSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = join(__dirname, '..');

// V1 per-jurisdiction layers. Each is a JSON array keyed by region_id (hospital proximity is a GeoJSON file whose
// features[].properties carry the record). A missing layer file is an empty layer.
export const V1_LAYERS = {
  legal_ownership:        'data/processed/legal-ownership.json',
  land_cost:              'data/processed/land-cost.json',
  hospital_proximity:     'data/processed/hospital-proximity.geojson',
  demographic_trajectory: 'data/processed/demographic-trajectory.json',
  soil_contamination:     'data/processed/soil-contamination.json',
  water_source_control:   'data/processed/water-source-control.json',
  climate_buffering:      'data/processed/climate-buffering.json',
};

// What the client reads (tests/schema.mjs CLIENT_LOOKUP_FIELDS is the same list). Values outside these sets are refused.
const CLIENT_ENUMS = {
  foreign_ownership_allowed: ['yes', 'restricted', 'no'],
  regulatory_direction: ['stable', 'tightening', 'loosening', 'volatile'],
  affordability_band: ['cheapest', 'low', 'moderate', 'premium', 'very_premium', 'unknown'],
  buffering_strength: ['very_low', 'low', 'moderate', 'high', 'very_high', 'unknown'],
};
const BAND_ORDER = ['cheapest', 'low', 'moderate', 'premium', 'very_premium'];

const HEADER_FULL =
  `// AUTO-GENERATED by scripts/gen_region_pages.mjs. Do not edit by hand.\n` +
  `// Re-run that script after any data/processed/*.json change.\n`;
const HEADER_CLIENT =
  `// AUTO-GENERATED by scripts/gen_v1_lookup.mjs. Do not edit by hand.\n` +
  `// Re-run that script after any data/processed/*.json change. Only the four fields the qualitative filters read are\n` +
  `// kept here; region pages and tests read data/processed/*.json directly.\n`;

export function loadV1Layers(root) {
  const out = {};
  for (const [layer, rel] of Object.entries(V1_LAYERS)) {
    const path = join(root, rel);
    if (!existsSync(path)) { out[layer] = {}; continue; }
    const raw = JSON.parse(readFileSync(path, 'utf8'));
    const records = Array.isArray(raw)
      ? raw
      : (raw.features || []).map((f) => f.properties || {});
    const byId = {};
    for (const rec of records) {
      if (rec && rec.region_id) byId[rec.region_id] = rec;
    }
    out[layer] = byId;
  }
  return out;
}

export function fullLookupText(v1) {
  return HEADER_FULL + `export const v1Lookup = ${JSON.stringify(v1, null, 2)};\n`;
}

// ---------------------------------------------------------------------------------------------------------------
// Band definition: the `band_edges` block of land-cost.metadata.yaml. Only the small subset this block uses is parsed
// (a block mapping with scalars and flow sequences), so the generator needs no YAML dependency.
//
//   band_edges:
//     unit: EUR            # the unit the edges are in, per hectare
//     edges: [5000, 10000, 20000, 40000]     # four ascending edges: cheapest < e1 <= low < e2 <= moderate < e3 <= premium < e4 <= very_premium
//   or
//   band_edges:
//     relative: true       # the bands are relative within the slate (the metadata says why); no edges are published
const scalar = (s) => {
  const t = s.replace(/\s+#.*$/, '').trim();
  if (/^-?\d+(\.\d+)?$/.test(t)) return Number(t);
  if (t === 'true') return true;
  if (t === 'false') return false;
  if (t === 'null' || t === '~') return null;
  const q = t.match(/^(["'])(.*)\1$/);
  return q ? q[2] : t;
};
export function parseBandEdges(yamlText) {
  const lines = yamlText.split(/\r?\n/);
  const start = lines.findIndex((l) => /^band_edges:\s*(#.*)?$/.test(l));
  if (start < 0) return null;
  const block = {};
  for (let i = start + 1; i < lines.length; i++) {
    const l = lines[i];
    if (/^\S/.test(l)) break; // next top-level key
    if (!l.trim() || /^\s*#/.test(l)) continue;
    const m = l.match(/^\s+([A-Za-z_][\w-]*):\s*(.*)$/);
    if (!m) continue;
    const [, key, rest] = m;
    const body = rest.replace(/\s+#.*$/, '').trim();
    if (body.startsWith('[')) {
      const inner = body.replace(/^\[/, '').replace(/\]$/, '');
      block[key] = inner.trim() ? inner.split(',').map((x) => scalar(x)) : [];
    } else block[key] = scalar(rest);
  }
  return block;
}
export function bandMeta(root) {
  const f = join(root, 'data/processed/land-cost.metadata.yaml');
  if (!existsSync(f)) throw new Error(`gen_v1_lookup: ${f} is missing (the band definition lives there)`);
  const be = parseBandEdges(readFileSync(f, 'utf8'));
  if (!be) throw new Error('gen_v1_lookup: land-cost.metadata.yaml has no `band_edges:` block (D9: the band definition must be recorded)');
  if (be.relative === true) return { relative: true };
  const unit = typeof be.unit === 'string' ? be.unit.trim() : '';
  const e = be.edges;
  const ok = unit && Array.isArray(e) && e.length === 4 && e.every((x) => typeof x === 'number' && Number.isFinite(x)) && e.every((x, i) => i === 0 || x > e[i - 1]);
  if (!ok) throw new Error('gen_v1_lookup: band_edges needs `unit` and four ascending numeric `edges`, or `relative: true`');
  return { unit, edges: e };
}

async function regionIds(root) {
  const f = join(root, 'data/regions.js');
  if (!existsSync(f)) return null;
  // data/regions.js is typeless ESM with no imports: loading it from a data: URL avoids Node's module-type reparse notice.
  const src = readFileSync(f, 'utf8');
  if (/^\s*import\s/m.test(src)) throw new Error('gen_v1_lookup: data/regions.js has imports; the coverage check cannot load it');
  const mod = await import('data:text/javascript;base64,' + Buffer.from(src).toString('base64'));
  return (mod.regions || []).map((r) => r.id);
}

const j = (v) => JSON.stringify(v);
const fmtLayer = (name, rows) =>
  `  ${j(name)}: {\n` + rows.map(([id, rec]) => `    ${j(id)}: ${rec}`).join(',\n') + `\n  }`;

export async function clientLookupText(v1, root) {
  const errors = [];
  const ids = await regionIds(root);
  const pick = {
    legal_ownership: (r) => ({ foreign_ownership: { allowed: r.foreign_ownership && r.foreign_ownership.allowed }, regulatory_direction: r.regulatory_direction }),
    land_cost: (r) => ({ affordability_band: r.affordability_band }),
    climate_buffering: (r) => ({ buffering_strength: r.buffering_strength }),
  };
  const checks = {
    legal_ownership: [['foreign_ownership.allowed', (r) => r.foreign_ownership && r.foreign_ownership.allowed, CLIENT_ENUMS.foreign_ownership_allowed], ['regulatory_direction', (r) => r.regulatory_direction, CLIENT_ENUMS.regulatory_direction]],
    land_cost: [['affordability_band', (r) => r.affordability_band, CLIENT_ENUMS.affordability_band]],
    climate_buffering: [['buffering_strength', (r) => r.buffering_strength, CLIENT_ENUMS.buffering_strength]],
  };
  const blocks = [];
  for (const layer of ['legal_ownership', 'land_cost', 'climate_buffering']) {
    const byId = v1[layer] || {};
    const order = ids || Object.keys(byId);
    const rows = [];
    for (const id of order) {
      const rec = byId[id];
      if (!rec) { errors.push(`${layer}: no record for ${id}`); continue; }
      for (const [path, get, allowed] of checks[layer]) {
        const v = get(rec);
        if (!allowed.includes(v)) errors.push(`${layer}/${id}.${path}=${j(v)} is not one of ${allowed.join('|')}`);
      }
      rows.push([id, j(pick[layer](rec))]);
    }
    if (ids) for (const id of Object.keys(byId)) if (!ids.includes(id)) errors.push(`${layer}: record for ${id}, which is not in data/regions.js`);
    blocks.push(fmtLayer(layer, rows));
  }
  if (errors.length) throw new Error('gen_v1_lookup (client): ' + errors.join('; '));
  const meta = bandMeta(root);
  return (
    HEADER_CLIENT +
    `export const v1Lookup = {\n${blocks.join(',\n')}\n};\n` +
    `// Band definition for affordability_band (data/processed/land-cost.metadata.yaml, band_edges), read by lib/qual-labels.js.\n` +
    `export const v1Meta = { affordability_band: ${j(meta)} };\n`
  );
}

// ---------------------------------------------------------------------------------------------------------------
function parseArgs(argv) {
  const o = { mode: 'client', root: DEFAULT_ROOT, out: null, check: false, write: false };
  const need = (i, a) => { if (i + 1 >= argv.length || argv[i + 1].startsWith('--')) { console.error(`gen_v1_lookup: ${a} needs an argument`); process.exit(2); } return argv[i + 1]; };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--check') o.check = true;
    else if (a === '--write') o.write = true;
    else if (a === '--mode') { o.mode = need(i, a); i++; }
    else if (a.startsWith('--mode=')) o.mode = a.slice(7);
    else if (a === '--root') { o.root = resolve(need(i, a)); i++; }
    else if (a.startsWith('--root=')) o.root = resolve(a.slice(7));
    else if (a === '--out') { o.out = resolve(need(i, a)); i++; }
    else if (a.startsWith('--out=')) o.out = resolve(a.slice(6));
    else { console.error(`gen_v1_lookup: unknown argument ${a}\nusage: node scripts/gen_v1_lookup.mjs [--mode client|full] [--root DIR] [--out FILE] [--check] [--write]`); process.exit(2); }
  }
  if (!['client', 'full'].includes(o.mode)) { console.error(`gen_v1_lookup: --mode must be client or full (got ${o.mode})`); process.exit(2); }
  if (o.write && o.check) { console.error('gen_v1_lookup: --write and --check are exclusive'); process.exit(2); }
  return o;
}

function diffHead(a, b, label) {
  const dir = mkdtempSync(join(tmpdir(), 'v1lookup-'));
  try {
    writeFileSync(join(dir, 'disk'), a); writeFileSync(join(dir, 'generated'), b);
    const r = spawnSync('diff', ['-u', '--label', `${label} (on disk)`, '--label', `${label} (generated)`, join(dir, 'disk'), join(dir, 'generated')], { encoding: 'utf8' });
    return (r.stdout || '').split('\n').slice(0, 40).join('\n');
  } finally { rmSync(dir, { recursive: true, force: true }); }
}

async function main() {
  const o = parseArgs(process.argv.slice(2));
  const v1 = loadV1Layers(o.root);
  let text;
  try {
    text = o.mode === 'full' ? fullLookupText(v1) : await clientLookupText(v1, o.root);
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
  const target = o.out || join(o.root, 'data/v1-lookup.js');
  if (o.check) {
    const disk = existsSync(target) ? readFileSync(target, 'utf8') : null;
    if (disk === text) { console.log(`gen_v1_lookup --check: OK (${o.mode} lookup, ${text.length} bytes, matches ${target})`); return; }
    console.error(`gen_v1_lookup --check: ${disk === null ? 'file missing' : 'DIFFERENT'}: ${target}`);
    if (disk !== null) console.error(diffHead(disk, text, 'data/v1-lookup.js'));
    console.error('Regenerate with: node scripts/gen_v1_lookup.mjs --write');
    process.exit(1);
  }
  if (o.write || o.out) {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, text);
    console.log(`gen_v1_lookup: wrote ${o.mode} lookup (${text.length} bytes) to ${target}`);
    return;
  }
  process.stdout.write(text);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
