#!/usr/bin/env node
// Integration report: applied / stale / skipped-low / needs-hand / held / dropped regions, with the reasons.
// Feeds the docs track's evidence addendum counts. Deterministic (no timestamp): a second run rewrites nothing.
//
//   node scripts/evidence/merge/report.mjs [--out-file evidence-out/integration-report.md] [--dry-run] [--root DIR] [--out DIR]
//
// Sections
//   1. what the converter found (counts from reverify/*.json, computed, never typed)
//   2. patches against the CURRENT data files (dry run): already applied (noop) / still to apply / stale / unresolved / unsupported
//   3. disposition ledger per owner and state
//   4. parked low-confidence items, needs-hand items, held items
//   5. dropped regions (verify/dropped-regions.json) and regions with more than 3 null cells
//   6. cross-check highlights (crosscheck.json) when present
import fs from 'node:fs';
import path from 'node:path';
import {
  parseArgs, resolveRoots, readJson, exists, writeIfChanged, buildIndex, printLine, isMain,
} from './common.mjs';
import { convert, summaryLines } from './reverify_to_patches.mjs';
import { patchFile, selectPatches } from './patch_js.mjs';
import { summary as dispositionSummary, nullCounts } from './disposition.mjs';

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
const clip = (s, n = 140) => { const t = cell(s); return t.length > n ? `${t.slice(0, n - 1)}...` : t; };

export async function buildReport(roots) {
  const lines = [];
  const L = (s = '') => lines.push(s);
  const conv = convert(roots);
  const index = buildIndex(roots.REVERIFY);
  L('# Integration report (evidence track)');
  L();
  L('Generated by `scripts/evidence/merge/report.mjs` from the files named below. Counts are computed, never typed.');
  L();
  L('## 1. Re-verification input');
  L();
  for (const l of summaryLines(conv, index)) L(`- ${l}`);

  L();
  L('## 2. Patches against the current data files (dry run)');
  L();
  const patchesFile = path.join(roots.OUT, 'patches.json');
  if (!exists(patchesFile)) L('`patches.json` does not exist yet: run `reverify_to_patches.mjs` first.');
  else {
    const all = selectPatches(readJson(patchesFile), { minConfidence: 'medium' });
    const byFile = new Map();
    for (const p of all) (byFile.get(p.file) || byFile.set(p.file, []).get(p.file)).push(p);
    const tot = { applied: 0, noop: 0, stale: 0, unresolved: 0, unsupported: 0 };
    const trouble = [];
    L('| file | patches | already applied | still to apply | stale | unresolved | unsupported |');
    L('|---|---|---|---|---|---|---|');
    for (const [file, patches] of [...byFile].sort()) {
      const abs = path.join(roots.ROOT, file);
      if (!exists(abs)) { L(`| ${file} | ${patches.length} | | | | ${patches.length} | |`); tot.unresolved += patches.length; continue; }
      const r = await patchFile(abs, patches, { dryRun: true });
      const c = { applied: 0, noop: 0, stale: 0, unresolved: 0, unsupported: 0 };
      for (const x of r.results) { c[x.state]++; tot[x.state]++; if (['stale', 'unresolved', 'unsupported'].includes(x.state)) trouble.push({ file, ...x }); }
      L(`| ${file} | ${patches.length} | ${c.noop} | ${c.applied} | ${c.stale} | ${c.unresolved} | ${c.unsupported} |`);
    }
    L(`| total | ${all.length} | ${tot.noop} | ${tot.applied} | ${tot.stale} | ${tot.unresolved} | ${tot.unsupported} |`);
    if (trouble.length) {
      L();
      L('Stale, unresolved and unsupported patches (nothing was written for them):');
      L();
      for (const t of trouble) L(`- ${t.state} \`${t.ref}\` ${t.file} \`${t.path}\`: ${clip(t.detail, 200)}`);
    }
  }

  L();
  L('## 3. Disposition ledger');
  L();
  L('| owner | rows | states |');
  L('|---|---|---|');
  for (const [o, c] of Object.entries(dispositionSummary(roots))) { const { rows, ...rest } = c; L(`| ${o} | ${rows} | ${Object.entries(rest).map(([k, v]) => `${k} ${v}`).join(', ')} |`); }

  L();
  L('## 4. Parked, hand-applied and held items');
  L();
  L(`### Low confidence, parked (${conv.deferredLow.length})`);
  L();
  for (const d of conv.deferredLow) L(`- \`${d.ref}\` ${d.file} \`${d.path}\`: ${clip(d.reason)}`);
  L();
  L(`### Needs hand (${conv.needsHand.length})`);
  L();
  for (const n of conv.needsHand) L(`- \`${n.ref}\` ${n.file} \`${n.path}\` (${n.owner}): ${cell(n.why)}`);
  L();
  L(`### Held by the converter (${conv.held.length})`);
  L();
  for (const h of conv.held) L(`- \`${h.ref}\` ${h.file} \`${h.path}\`: state held-human-review; ${clip(h.reason)}`);
  L();
  L(`### Handed to the docs track (deeper.html): ${conv.deeper.length} item(s) in deeper-change-list.json`);

  L();
  L('## 5. Regions');
  L();
  const dropped = path.join(roots.UPG, 'verify/dropped-regions.json');
  if (exists(dropped)) {
    const d = readJson(dropped);
    const rows = Array.isArray(d) ? d : (d.dropped || d.regions || []);
    L(`Dropped regions (${rows.length}):`);
    for (const r of rows) L(`- ${typeof r === 'string' ? r : `${r.id || r.regionId}: ${clip(r.reason || r.why || '')}`}`);
  } else L('No `verify/dropped-regions.json`: no region has been dropped.');
  L();
  const regionsFile = path.join(roots.ROOT, 'data/regions.js');
  if (exists(regionsFile)) {
    try {
      const nc = (await nullCounts(regionsFile)).filter((c) => c.nulls > 0);
      L(nc.length ? `Regions with null cells: ${nc.map((c) => `${c.id} (${c.nulls})`).join(', ')}.` : 'No region has a null cell.');
    } catch (e) { L(`Null cells could not be counted: ${cell(e.message)}`); }
  }

  const cc = path.join(roots.OUT, 'crosscheck.json');
  if (exists(cc)) {
    L();
    L('## 6. Cross-check highlights');
    L();
    const j = readJson(cc);
    const rows = j.rows || [];
    const by = {};
    for (const r of rows) if (r.exceeds && r.exceeds.length) by[r.criterion] = (by[r.criterion] || 0) + 1;
    L(`${rows.length} (region, criterion) rows; exceedances per criterion: ${Object.entries(by).map(([k, v]) => `${k} ${v}`).join(', ') || 'none'}.`);
  }
  return `${lines.join('\n')}\n`;
}

export async function run(argv) {
  const args = parseArgs(argv, { boolFlags: ['dry-run'] });
  const roots = resolveRoots(args);
  const text = await buildReport(roots);
  const file = path.resolve(args.outFile && args.outFile !== true ? args.outFile : path.join(roots.OUT, 'integration-report.md'));
  const r = writeIfChanged(file, text, { dryRun: !!args.dryRun });
  printLine(`report: ${path.relative(process.cwd(), file)}: ${r}`);
  return 0;
}
if (isMain(import.meta.url)) run(process.argv.slice(2)).then((c) => process.exit(c), (e) => { process.stderr.write(`report: ${e.stack || e}\n`); process.exit(1); });
